### ISSUE TITLE
Migrate to Null safety (Resolved in 2.0.0)

### ISSUE THREAD

**Issue by savs90** [wooxist/unique_ids#2]
Hello there! Just wondering with flutter 2 announcing and null safety official in stable channel would it be possible to migrate this plugin to null safety?

Thanks for the great work!

**Comment by wooxist** [comment]
OK. ASAP I'll do it!

**Comment by savs90** [comment]
Great! Thank you , very much!

**Comment by wooxist** [comment]
Please update 2.0.0

**Comment by wooxist** [comment]
@savs90  Was it resolved? please close this issue.
